version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: blog-postgres
    restart: always
    environment:
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: blog_pass
      POSTGRES_DB: blog_db           
    ports:
      - "5432:5432"
    volumes:
      - blog_data:/var/lib/postgresql/data
    networks:
      - blog-network

volumes:
  blog_data:

networks:
  blog-network:
